### ISSUE TITLE
Move progressbar to code_ext?

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#10]
The function `progressbar` in ../code/FSI should perhaps move to the folder code_ext since it looks like it was obtained from: 
https://uk.mathworks.com/matlabcentral/fileexchange/6922-progressbar

Side note, for the simple use shown in this toolbox, it seems the default `waitbar` function (https://uk.mathworks.com/help/matlab/ref/waitbar.html) would also be sufficient.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks, moved it to code_ext and added license file.
