### ISSUE TITLE
Check for folder existence before attempting creation

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#11]
In the code `FSI_unsteady` (line 725) it says `mkdir(strcat(pwd,filesep,'data'));`, which attempts to create the folder, this currently produces this warning if the folder already exists: 
```matlab
Warning: Directory already exists. 
> In FSI_unsteady (line 725)
In FSI_unsteady_main (line 88)
In initializeUnsteadyFSI (line 51)
In runUnsteadyFSItestcases (line 30)
In example2_NACA6418_unsteadyFSI (line 96) 
```
I suggest you add checks for the existence of folders prior to attempting their creation to avoid such warnings.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman added checks, thanks!
