### ISSUE TITLE
Unable to run examples as XFOIL executables for Linux are missing

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#4]
I use Ubuntu 22.04. Upon running the examples I get the following error: 

```matlab
Error using XFOIL/run
Unix version not yet implemented!

Error in preCalcVisc (line 44)
    xf.run

Error in generateWingModelAero (line 511)
viscPre = preCalcVisc(wingDesign.airfoil,wingDesign.chord);

Error in example1_NACA0012_FSI_modal_vs_displacement (line 48)
    wingModelAero = generateWingModelAero(wingDesign,simParam,wingModelStructure);
```
Which relates to line 88 in: 
`/FlexWingROM/code/code_ext/XFOIL/@XFOIL/XFOIL.m`. Essentially you currently only provide a Windows executable `xfoil.exe`. 

It does look like the full source fro XFOIL is available online ( as well as a version for linux compilation): https://web.mit.edu/drela/Public/web/xfoil/. I have attempted to compile that, but gave up when I was unable to install the required Intell Fortran compilers. 

Can you do one of the following: 
1) Make your software work fully for Linux and clarify all steps/instructions required. Perhaps you can then also include guidance on my Intell compiler issue. 
2) Clarify that your software is only developed and tested for Windows and that, although use for Linux may be possible, it is not currently supported. 

If you choose option 2, I will have to end my review for JOSS for this submission, as I cannot proceed. I will check if a colleague running Windows is able to help.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks for the comments! XFOIL is only used to precalculate viscous drag and maximum lift coefficient of the airfoil. I defined tables with precalculated XFOIL coefficients (for the two airfoils that are used) that are loaded directly in case the user runs the code on Linux.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman yes I included a statement in generateWingModelAero.m that checks if the code is running on windows (line 512 if ispc), and load XFOIL data in case it's not running on windows.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks
