### ISSUE TITLE
rethrowing error messages to help with debugging

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#6]
Throughout several codes `try` and `catch` statements are used e.g. like this: 
```matlab
try 
    load data/unitTest1data
catch
    error('Could not load test 1 data')
end
``` 
However if the custom error message is reached the used cannot easily debug what is wrong as the actual underlying error trail is note exposed. I recommend you actually `catch` the error and `rethrow` it, i.e. use the equivalent of the below throughout to present the original error message as well: 
```matlab
try 
    load(fullfile(mainPath,'data','unitTest1data'));
catch ME
    warning('Could not load test 1 data');
    rethrow(ME);
end
```

**Comment by Kevin-Mattheus-Moerman** [comment]
A related issue is the use of  `assert`. 

The format for the `assert` function should be `assert(cond,msg)` where the error message `msg` is thrown when the condition `cond` is false. The code currently contains the use of `assert` without message, this is not useful. Please add messages where ever you use this or remove `assert`.
e.g.
```matlab
assert(abs(wingDesign.nRibsC - wingDesign_true.nRibsC) < tol)
assert(abs(simParam.addMM - simParam_true.addMM) < tol)
```
Without the message it says "assertion failed" which offers no information as to what failed.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks! Included rethrow and assert message.
