### ISSUE TITLE
Switch to use modern "clear" synstax

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#7]
Throughout the following is used: 
```matlab
clear all
close all
clc
```
In newer versions of MATLAB one will notice then that the `all` in `clear all` is underlined in red. This is because in modern MATLAB syntax the `all` can likely be dropped. 

Hence I would propose the following: 
```matlab
clear; close all; clc; % Clearing workspace, closing all figures, clearing command window
```

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks, changed to use the new syntax now.
