### ISSUE TITLE
Recommended: Add a .gitignore file and ignore MATLAB temporary files .asv

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#8]
Add a file called `.gitignore` to your main folder and have it contain: 
```
#Ignore MATLAB temporary files
*.asv
```
This way MATLAB's temporary files will be ignored.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman added gitignore file

**Comment by Kevin-Mattheus-Moerman** [comment]
Great, nearly there, remove the extension so rename it from `.gitignore.txt` to `.gitignore`

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks, slowly getting there:) removed the wrong extension
