### ISSUE TITLE
Input question unclear in clearOldAnimationV

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [urban-fasel/FlexWingROM#9]
For example 2 I get a question from `clearOldAnimationV` which says: _sure to delete the existing pitching FSI animation data ?_. I tried `yes`, then `y` and then finally `1`. I suggest you change the question to inform the user what the input format is, e.g.: 

`sure to delete the existing pitching FSI animation data ? (1=yes, 0=no)`

Change this throughout if there are more such inputs requested.

**Comment by urban-fasel** [comment]
@Kevin-Mattheus-Moerman thanks, changed it accordingly.
